// <auto-generated />
using System;
using Entra21_TCC_BackEnd_UpCommerce.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entra21_TCC_BackEnd_UpCommerce.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20250826010340_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Entra21_TCC_BackEnd_UpCommerce.Models.Cdk", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CdkId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ParentCdkId")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCdkId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Cdks");
                });

            modelBuilder.Entity("Entra21_TCC_BackEnd_UpCommerce.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UrlLogo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Entra21_TCC_BackEnd_UpCommerce.Models.Style", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlignSelf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BorderColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("BorderRadiusBottomLeft")
                        .HasColumnType("int");

                    b.Property<int>("BorderRadiusBottomRight")
                        .HasColumnType("int");

                    b.Property<int>("BorderRadiusTopLeft")
                        .HasColumnType("int");

                    b.Property<int>("BorderRadiusTopRight")
                        .HasColumnType("int");

                    b.Property<int>("BorderSize")
                        .HasColumnType("int");

                    b.Property<string>("BorderType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Bottom")
                        .HasColumnType("int");

                    b.Property<string>("CdkId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cursor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Display")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FlexAlign")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FlexAlignItems")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FlexDirection")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FlexGap")
                        .HasColumnType("int");

                    b.Property<string>("FlexJustify")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FlexWrap")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FontFamily")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FontSize")
                        .HasColumnType("int");

                    b.Property<string>("FontWeight")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("HoverBorderRadius")
                        .HasColumnType("int");

                    b.Property<string>("HoverScale")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("HoverShadowBlur")
                        .HasColumnType("int");

                    b.Property<string>("HoverShadowColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("HoverShadowX")
                        .HasColumnType("int");

                    b.Property<int>("HoverShadowY")
                        .HasColumnType("int");

                    b.Property<string>("IconSource")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageSource")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Left")
                        .HasColumnType("int");

                    b.Property<string>("LinkSource")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MarginBottom")
                        .HasColumnType("int");

                    b.Property<int>("MarginLeft")
                        .HasColumnType("int");

                    b.Property<int>("MarginRight")
                        .HasColumnType("int");

                    b.Property<int>("MarginTop")
                        .HasColumnType("int");

                    b.Property<string>("NewComponentId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Opacity")
                        .HasColumnType("double");

                    b.Property<int>("PaddingBottom")
                        .HasColumnType("int");

                    b.Property<int>("PaddingLeft")
                        .HasColumnType("int");

                    b.Property<int>("PaddingRight")
                        .HasColumnType("int");

                    b.Property<int>("PaddingTop")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Right")
                        .HasColumnType("int");

                    b.Property<int>("ShadowBlur")
                        .HasColumnType("int");

                    b.Property<string>("ShadowColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ShadowX")
                        .HasColumnType("int");

                    b.Property<int>("ShadowY")
                        .HasColumnType("int");

                    b.Property<string>("TextAlign")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TextContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Top")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.Property<int>("ZIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CdkId")
                        .IsUnique();

                    b.ToTable("Styles");
                });

            modelBuilder.Entity("Entra21_TCC_BackEnd_UpCommerce.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("urlInstagram")
                        .HasColumnType("longtext");

                    b.Property<string>("urlLinkedin")
                        .HasColumnType("longtext");

                    b.Property<string>("urlPhoto")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Entra21_TCC_BackEnd_UpCommerce.Models.Cdk", b =>
                {
                    b.HasOne("Entra21_TCC_BackEnd_UpCommerce.Models.Cdk", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentCdkId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Entra21_TCC_BackEnd_UpCommerce.Models.Project", "Project")
                        .WithMany("Component")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Parent");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Entra21_TCC_BackEnd_UpCommerce.Models.Project", b =>
                {
                    b.HasOne("Entra21_TCC_BackEnd_UpCommerce.Models.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entra21_TCC_BackEnd_UpCommerce.Models.Style", b =>
                {
                    b.HasOne("Entra21_TCC_BackEnd_UpCommerce.Models.Cdk", "Cdk")
                        .WithOne("Style")
                        .HasForeignKey("Entra21_TCC_BackEnd_UpCommerce.Models.Style", "CdkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cdk");
                });

            modelBuilder.Entity("Entra21_TCC_BackEnd_UpCommerce.Models.Cdk", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Style");
                });

            modelBuilder.Entity("Entra21_TCC_BackEnd_UpCommerce.Models.Project", b =>
                {
                    b.Navigation("Component");
                });

            modelBuilder.Entity("Entra21_TCC_BackEnd_UpCommerce.Models.User", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
